project:
  type: website
  output-dir: docs

website:
  title: "Wesley Neves"
  description: "Oceanógrafo | Ecologia Marinha | Data Science"
  
  navbar:
    background: white
    search: true
    left:
      - href: sobre/about.qmd
        text: "🪪 Sobre"
      - href: posts/index.qmd
        text: "📝 Blog/Dicas"
      - href: cursos/index.qmd
        text: "🎓  Cursos"
      - href: livros/index.qmd
        text: "🪪 Livros"         
      - href: contato/index.qmd
        text: "📲 Contato" 
      

format:
  html:
    theme: litera
    css: styles.css
    toc: false
    lang: pt

render:
  - "*.qmd"
  - "posts/*.qmd"